### PR TITLE
Add support for ‘www.hyperium.cc’

### PR DESCRIPTION
**Pull request by RDIL**
This way, www.hyperium.cc will redirect to the main site instead of 404ing. 
@CoalCoding

### CODE REVIEW

**Comment by CoalCoding** [comment]
It redirects me to the main site, doesn't give me a 404.

**Comment by RDIL** [comment]
Huh that’s odd, it’s still 404ing for me, and the SEO tests have a higher score with this addition.  I’ll close this if you want.

**Comment by CoalCoding** [comment]
I've confirmed with the other members of the team that it works for them. Could be an issue with your DNS server?

**Comment by RDIL** [comment]
Yeah, my internet is kinda odd

**Pull request closed without merging**
